[server]
port = 4000
host = "127.0.0.1"

[tls]
enabled = false

[logging]
level = "info"

[notary_key]
type = "file"
path = "notary_key.pem"

[notarization]
max_sent_data = 1024  # 1MB
max_recv_data = 1024  # 1MB 